name: Build and deploy my app with reusable

on:
  push:
    paths:
      - 'src/**'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  reusable-build-job:

    uses: ./.github/workflows/reusable-build.yml
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}

  reusable-deploy-job:
    needs: reusable-build-job

    uses: ./.github/workflows/reusable-deploy.yml
    with:
      package-name: .net-app
      app-name: gh-200-test
      deployment-slot: production
    secrets:
      azure-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        
    
