name: Reusable workflow to deploy app

on:
  workflow_call:
    inputs:
        package-name:
            required: true
            type: string
        app-name:
            required: true
            type: string
        deployment-slot:
            required: true
            type: string
    secrets:
        azure-profile:
            required: false

jobs:
  deploy-job:
    runs-on: ubuntu-latest
    
    environment:
      name: ${{inputs.deployment-slot}}
      url: ${{steps.deploy-azure.outputs.webapp-url}}

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4.3.0
        with:
          name: ${{inputs.package-name}}

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v3
        id: deploy-azure
        with:
          app-name: ${{inputs.app-name}}
          slot-name: ${{inputs.deployment-slot}}
          package: .
          publish-profile: ${{secrets.azure-profile}}
