name: Reusable workflow to deploy app

on:
  workflow_call:
    inputs:
        package-name:
            required: true
            type: string
        app-name:
            required: true
            type: string
        deployment-slot:
            required: true
            type: string
    secrets:
        azure-profile:
            required: false

jobs:
  deploy-job:
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4.3.0
        with:
          name: ${{inputs.package-name}}

      - name: Deploy to Azure App Service
        run: echo "Value of secret is - ${{secrets.azure-profile == 'Placeholder'}}"
